Repository lf-lang/vscode-lingua-franca, pull requests merged in 2022-07, with the labels that each got.

#66 Fix import statement highlighting
  syntax/lflang.tmLanguage.json
Labels: bug, highlighting

#74 Fix to npm `clean` script
  package.json
Labels: bug

#75 Exit when unable to checkout lingua-franca and its submodules
  src/build_lds.ts
Labels: bug, build
