Repository lf-lang/vscode-lingua-franca, pull requests merged in 2024-10, with the labels that each got.

#156 Lingua Franca Package Explorer: extensions to UI in VScode plugin
  .gitignore
  .vscode/launch.json
  README.md
  images/logo/lf-logo-dark.svg
  images/logo/lf-logo-light.svg
  package.json
  src/extension.ts
  src/extension_version.ts
  src/lfview/lf-data-provider-commands.ts
  src/lfview/lf-data-provider.ts
  syntaxes/lflang.tmLanguage.json
Labels: feature

#183 Resolve goToLingoToml for Windows
  package.json
  src/extension.ts
  src/lfview/lf-data-provider-commands.ts
  src/lfview/lf-data-provider.ts
Labels: bugfix

#182 Update documentation link
  package.json
Labels: documentation
